// Main films
export const FILMS_MAIN_FETCHING = 'FILMS_MAIN_FETCHING';
export const FILMS_MAIN_SUCCESS = 'FILMS_MAIN_SUCCESS';
export const FILMS_MAIN_FAIL = 'FILMS_MAIN_FAIL';

// Popular films
export const FILMS_POPULAR_FETCHING = 'FILMS_POPULAR_FETCHING';
export const FILMS_POPULAR_SUCCESS = 'FILMS_POPULAR_SUCCESS';
export const FILMS_POPULAR_FAIL = 'FILMS_POPULAR_FAIL';

// Add new films
export const MYFILMS_ADD_FETCHING = 'MYFILMS_ADD_FETCHING';
export const MYFILMS_ADD_SUCCESS = 'MYFILMS_ADD_SUCCESS';
export const MYFILMS_ADD_FAIL = 'MYFILMS_ADD_FAIL';

// Get new films
export const MYFILMS_GET_FETCHING = 'MYFILMS_GET_FETCHING';
export const MYFILMS_GET_SUCCESS = 'MYFILMS_GET_SUCCESS';
export const MYFILMS_GET_FAIL = 'MYFILMS_GET_FAIL';